---
functional:
  - Требование 3
  - Требование 4
  - Требование 8
  - Требование 9
non-functional:
  - Требование 1
  - Требование 2
  - Требование 5
  - Требование 6
  - Требование 7
  - Требование 10
implicit:
  - Требование 11
  - Требование 12
implicit1: #Установка место для баннера рекламы
           #Возможность менять тему приложения
